apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    project: k8s
spec:
  template:
    spec:
      containers:
        - name: django-migrate
          image: woodstock93/api_server:1
          command: ["/bin/sh", "-c"]
          args:
            - |
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py makemigrations dev &&
              python manage.py migrate
              yes | python manage.py collectstatic
          envFrom:
            - configMapRef:
                name: my-config              
          env:
            - name: DATABASE_URL
              value: psql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(APP_SERVICE_NAME):5432/$(POSTGRES_DB)


      restartPolicy: Never
  backoffLimit: 5