apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-app
    project: k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
        project: k8s
    spec:
      containers:
      - name: django-app
        image: woodstock93/api_server:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: my-config
        env:
        - name: DATABASE_URL
          value: psql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(APP_SERVICE_NAME):5432/$(POSTGRES_DB)
        volumeMounts:
          - name: static-files
            mountPath: /staticfiles
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: django-static-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-service
    project: k8s
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: django-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  labels:
    project: k8s
spec:
  defaultBackend:
    service:
      name: django-service
      port:
        number: 80

---
apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    project: k8s
spec:
  template:
    spec:
      containers:
        - name: django-migrate
          image: woodstock93/api_server:1
          command: ["/bin/sh", "-c"]
          args:
            - |
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py makemigrations dev &&
              until python manage.py migrate; do echo "Retrying migrate..."; sleep 3; done &&
              yes | python manage.py collectstatic
          envFrom:
            - configMapRef:
                name: my-config              
          env:
            - name: DATABASE_URL
              value: psql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(APP_SERVICE_NAME):5432/$(POSTGRES_DB)
      restartPolicy: Never
  backoffLimit: 5