apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-static-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/django/static"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
